### ISSUE TITLE
Manually setting command argument delimiter only respected if delimiter is found in command

### ISSUE THREAD

**Issue by jhelwig** [zeyla/serenity#181]
As part of exploring what was going on with #180 I tried setting various argument delimiter settings. I was surprised to see that the manually specified argument delimiter setting was only used if the string was found in the arguments to the command. If the manually specified delimiter wasn't found, it would always use a single space as the delimiter. https://github.com/zeyla/serenity/blob/caf69d66893c2688f0856cc33f03702071d1314a/src/framework/standard/mod.rs#L909-L910

I was wondering what the intent behind this behavior was as it was rather surprising, and didn't seem to be documented (https://docs.rs/serenity/0.4.0/serenity/framework/standard/struct.Configuration.html#method.delimiter).

**Comment by acdenisSK** [comment]
It defaults to a space since that's the most used delimiter in bots. But i agree that i should've added some docs regarding that behaviour.

**Comment by jhelwig** [comment]
I completely understand the general default of using spaces. https://github.com/zeyla/serenity/blob/598252365c189b5b8b83a1a131a2d45df29516fd/src/framework/standard/configuration.rs#L446

That seems to be a separate discussion though. I'm surprised by overriding the manually specified delimiter with a single space when the user's specified delimiter isn't found.

**Comment by acdenisSK** [comment]
Oops, should've added more context on that part, welp.

Let's use [this](https://play.rust-lang.org/?gist=8af7b42bea6c05efc02f47227179709e&version=stable) as a start on explaining with the "if the manually put delimiter of the user isn't found in the message, default to a space" stuff.

So suppose with the first case, we'd indeed use the passed delimiter; but we can't do much with the input in regards to `Args`'s api, since the moment you do `Args::single::<String>` or something, it's over.
But with the second case, we _can_ at least get some input to mess with, parse, etc.

Though, i chose to default to a space for another reason, if multiple delimiters are passed (`[", ", ". "]`), then which delimiter should be used for splitting the message if either of them isn't even found in the message? With the first one probably, but as i mentioned earlier, we'd get the useless input.
So a space was a reasonable solution to keep things at least nice.

**Comment by jhelwig** [comment]
So, I don't really think the "usefulness" of the result of`"42. 55".split(", ")` is really the point. If a user configured the bot with `c.delimiters(vec![", "])` then they asked that arguments only be split using `", "`.

Consider a command configured with `min_args(2)`, and a bot configured with `delimiters(vec![", "])`. If the bot sees `!command first argument` instead of `!command first argument, second argument` I would expect the command to fail, instead of being run with `["first", "argument"]`.

If the bot was configured with `delimiters(vec![", ", " "])` then I would expect `!command first argument` to result in `["first", "argument"]`.

If the user wants the fall-back behavior to using `" "` to split they can always have it in their `delimiters` list, however there is currently no way to _not_ have this fall-back behavior so that `!command first argument` would fail if it has `min_args(2)`.

**Comment by acdenisSK** [comment]
Hmm, good point actually.
Well, i'll change the behaviour to this tomorrow to settle this issue down. (Or if you happen to pr it first)

**Comment by jhelwig** [comment]
I should have a PR up for this in a bit, since while working on the PR for #180, it made sense to restructure how the delimiter is handled.

**Comment by hsiW** [comment]
Closed by https://github.com/zeyla/serenity/pull/183
