### ISSUE TITLE
Now that the master branch is gone, some links are broken

### ISSUE THREAD

**Issue by Majora320** [zeyla/serenity#230]
e.g. the examples link in https://docs.rs/serenity/0.4.3/serenity/

**Comment by zeyla** [comment]
Initially, we used the master branch as our in-development branch for the next version. This is problematic, because if it's a breaking version, then the example in the README and the examples directory won't work with the latest released version.

We had the initial idea of using a branch for each version (including the intended next version), but this just doesn't work, with one reason being the one you mentioned.

As a solution, the most recent version will be the `master` branch, and the in-development branch(es) will be named according to their intended version.

Thanks for the report.

**Comment by MOZGIII** [comment]
I propose renaming `master` branch to `stable` - that's the usual thing for such workflows.
